#include <libgen.h>
#include <spawn.h>
#include <limits.h>
#include <regex.h>
#include <tar.h>
#include <complex.h>
#include <math.h>
#include <stdlib.h>
#include <locale.h>
#include <assert.h>
#include <elf.h>
#include <reent.h>
#include <stdio.h>
#include <fcntl.h>
#include <wordexp.h>
#include <langinfo.h>
#include <errno.h>
#include <search.h>
#include <dirent.h>
#include <devctl.h>
#include <stdatomic.h>
#include <time.h>
#include <alloca.h>
#include <ar.h>
#include <_ansi.h>
#include <termios.h>
#include <unistd.h>
#include <signal.h>
#include <setjmp.h>
#include <newlib.h>
#include <fenv.h>
#include <inttypes.h>
#include <wchar.h>
#include <iconv.h>
#include <sched.h>
#include <ctype.h>
#include <getopt.h>
#include <pwd.h>
#include <paths.h>
#include <wctype.h>
#include <_newlib_version.h>
#include <pthread.h>
#include <ndbm.h>
#include <ieeefp.h>
#include <_syslist.h>
#include <stdio_ext.h>
#include <tgmath.h>
#include <regdef.h>
#include <fnmatch.h>
#include <grp.h>
#include <ftw.h>
#include <memory.h>
#include <cpio.h>
#include <semaphore.h>
#include <unctrl.h>
#include <envlock.h>
#include <malloc.h>
#include <argz.h>
#include <fastmath.h>
#include <envz.h>
#include <strings.h>
#include <utmp.h>
#include <stdint.h>
#include <string.h>
#include <utime.h>
#include <threads.h>
#include <glob.h>
#include <sys/stat.h>
#include <sys/_timeval.h>
#include <sys/_timespec.h>
#include <sys/reent.h>
#include <sys/_locale.h>
#include <sys/iconvnls.h>
#include <sys/stdio.h>
#include <sys/fcntl.h>
#include <sys/errno.h>
#include <sys/param.h>
#include <sys/timeb.h>
#include <sys/queue.h>
#include <sys/features.h>
#include <sys/dirent.h>
#include <sys/time.h>
#include <sys/lock.h>
#include <sys/types.h>
#include <sys/unistd.h>
#include <sys/signal.h>
#include <sys/timespec.h>
#include <sys/times.h>
#include <sys/fenv.h>
#include <sys/sched.h>
#include <sys/_types.h>
#include <sys/dir.h>
#include <sys/tree.h>
#include <sys/config.h>
#include <sys/_stdint.h>
#include <sys/_tz_structs.h>
#include <sys/custom_file.h>
#include <sys/syslimits.h>
#include <sys/wait.h>
#include <sys/cdefs.h>
#include <sys/_pthreadtypes.h>
#include <sys/file.h>
#include <sys/resource.h>
#include <sys/_sigset.h>
#include <sys/statvfs.h>
#include <sys/_default_fcntl.h>
#include <sys/select.h>
#include <sys/iosupport.h>
#include <sys/string.h>
#include <sys/utime.h>
#include <sys/_intsup.h>
#include <libfatversion.h>
#include <mm_types.h>
#include <nds.h>
#include <gl2d.h>
#include <dswifi_version.h>
#include <dswifi9.h>
#include <dswifi7.h>
#include <fat.h>
#include <netdb.h>
#include <gbfs.h>
#include <maxmod7.h>
#include <maxmod9.h>
#include <filesystem.h>
